version: '3'

services:
  php:
    image: php:8.2-fpm
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - app-network

  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
      ###<

networks:
  app-network:
    driver: bridge

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
