version: '3'

services:
  php:
    image: php:7.4-fpm
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - app-network
    working_dir: /var/www/html
    command: tail -f /dev/null

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-123456}
    volumes:
      - database_data:/var/lib/mysql:rw
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  database_data:


